spring:
  application:
    name: loader

app:
  api-key: ${API_KEY:some_key}
  local:
    save-always: true
    directory: "./data/backlog"

  minio:
    username: ${MINIO_USERNAME:root}
    password: ${MINIO_PASSWORD:12345678}
    url: ${MINIO_URL:http://localhost:9000}
    bucket-name: repositories
    records-per-file: 1000
